//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_buss.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sistemaviajesbusEntities : DbContext
    {
        public sistemaviajesbusEntities()
            : base("name=sistemaviajesbusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<disponibilidad> disponibilidad { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<reservar> reservar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<unidades> unidades { get; set; }
        public virtual DbSet<viajes> viajes { get; set; }
    
        public virtual int inserta_clientes(string nombre_cli, string apellidos_cli, string direccion_cli, string dni_cli, string telefono_cli, string usuario_cli, string clave_cli, Nullable<System.DateTime> fecha_cli)
        {
            var nombre_cliParameter = nombre_cli != null ?
                new ObjectParameter("nombre_cli", nombre_cli) :
                new ObjectParameter("nombre_cli", typeof(string));
    
            var apellidos_cliParameter = apellidos_cli != null ?
                new ObjectParameter("apellidos_cli", apellidos_cli) :
                new ObjectParameter("apellidos_cli", typeof(string));
    
            var direccion_cliParameter = direccion_cli != null ?
                new ObjectParameter("direccion_cli", direccion_cli) :
                new ObjectParameter("direccion_cli", typeof(string));
    
            var dni_cliParameter = dni_cli != null ?
                new ObjectParameter("dni_cli", dni_cli) :
                new ObjectParameter("dni_cli", typeof(string));
    
            var telefono_cliParameter = telefono_cli != null ?
                new ObjectParameter("telefono_cli", telefono_cli) :
                new ObjectParameter("telefono_cli", typeof(string));
    
            var usuario_cliParameter = usuario_cli != null ?
                new ObjectParameter("usuario_cli", usuario_cli) :
                new ObjectParameter("usuario_cli", typeof(string));
    
            var clave_cliParameter = clave_cli != null ?
                new ObjectParameter("clave_cli", clave_cli) :
                new ObjectParameter("clave_cli", typeof(string));
    
            var fecha_cliParameter = fecha_cli.HasValue ?
                new ObjectParameter("fecha_cli", fecha_cli) :
                new ObjectParameter("fecha_cli", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserta_clientes", nombre_cliParameter, apellidos_cliParameter, direccion_cliParameter, dni_cliParameter, telefono_cliParameter, usuario_cliParameter, clave_cliParameter, fecha_cliParameter);
        }
    }
}
