//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_buss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disponibilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disponibilidad()
        {
            this.viajes = new HashSet<viajes>();
        }
    
        public int codigo_dis { get; set; }
        public Nullable<int> codigo_un { get; set; }
        public string origen_dis { get; set; }
        public string destino_dis { get; set; }
        public Nullable<System.DateTime> fecha_dia_dis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viajes> viajes { get; set; }
    }
}
