//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace CRUD_buss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.unidades = new HashSet<unidades>();
        }
    
        public int codigo_emp { get; set; }
        [Required]
        public string perfil_emp { get; set; }
        [Required]
        public string nombre_emp { get; set; }
        public string ruck_emp { get; set; }
        public string direccion_emp { get; set; }
        public string telefono_emp { get; set; }
        [Required]
        public Nullable<int> valoracion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unidades> unidades { get; set; }
    }
}
