//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_buss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int codigo_per { get; set; }
        public string nombre_per { get; set; }
        public string apellidos_per { get; set; }
        public string direccion_per { get; set; }
        public string dni_per { get; set; }
        public string telefono_per { get; set; }
        public string usuario_per { get; set; }
        public string clave_per { get; set; }
        public Nullable<System.DateTime> fecha_per { get; set; }
    }
}
