//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_buss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservar
    {
        public int codigo_res { get; set; }
        public Nullable<int> codigo_bus { get; set; }
        public Nullable<int> codigo_cl { get; set; }
        public string estado_res { get; set; }
        public Nullable<System.DateTime> fecha_res { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual unidades unidades { get; set; }
    }
}
