//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_buss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unidades()
        {
            this.reservar = new HashSet<reservar>();
            this.viajes = new HashSet<viajes>();
        }
    
        public int codigo_uni { get; set; }
        public Nullable<int> codigo_em { get; set; }
        public string nombre_uni { get; set; }
        public Nullable<int> aciento_uni { get; set; }
        public string estado_uni { get; set; }
        public Nullable<System.TimeSpan> hora_dis { get; set; }
        public Nullable<double> tarifa_uni { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservar> reservar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viajes> viajes { get; set; }
    }
}
